blank_issues_enabled: false
contact_links:
  - name: Question
    url:  https://github.com/polyphene/kythera/discussions/new?category=q-a
    about: Please ask questions in the Kythera GitHub Discussions forum.
